# This file should reside in $HOME/.config/starship.toml

# Prompt layout
format = """$directory$git_branch$git_commit$git_state$git_status$character"""
right_format = """$all"""

# Inserts a blank line between shell prompts
#add_newline = true

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true

## section from github.com/ryo-ARAKI

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

##

[git_status]
conflicted = " ğŸ’¥ "
ahead = " â–¶Ã—${count} "
behind = " â—€Ã—${count} "
diverged = " â„¹: â–¶Ã—${ahead_count} â—€Ã—${behind_count} "
untracked = " ğŸ”Ã—${count} "
stashed = " ğŸ—„ "
modified = " ğŸ“‘Ã—${count} "
staged = " ğŸ“Ã—${count} "
renamed = " ğŸ·Ã—${count} "
deleted = " ğŸ—‘ï¸Ã—${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[line_break]
disabled = true

[character]
success_symbol = "[ ï‡  â¯](bold green) "
error_symbol = "[ ï‡‘  â¯](bold red) "

[memory_usage]
disabled = false

[git_branch]
symbol = "ï„“  îœ¥ "

[git_metrics]
disabled = true

[conda]
format = "[$symbol conda env: $environment]($style) "
truncation_length = 0
symbol = "îˆµ"
style = "fg:155"
ignore_base = true
disabled = false
